# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
parameters:
  - name: vcpkgToolSha
    displayName: 'Custom SHA of vcpkg-tool to use rather than bootstrap'
    type: string
    default:  'bad94627a10174f69e91b688a0aa2ece08ef6ee1'
  - name: tripletPattern
    displayName: 'Enable triplets which contain this substring (^ matches begin, $ matches end)'
    type: string
    default: '^'

jobs:
- template: linux/azure-pipelines.yml
  parameters:
    jobName: x64_linux
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}
